blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/contentful/contentful-batch-libs/blob/master/README.md
    about: Check out our documentation for help and guides
